### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by damn-good** [soeirosantos/simple-oauthserver#1]
I've build your project. But I don't know how to use it. Please make you readme more detailed.
Hello there...
Has anyone been able to run the flow shown in br.com.caelum.oauth.clients package?

**Comment by eniniz** [comment]
+1

**Comment by soeirosantos** [comment]
Hi guys, sorry by the late answer.

Observe that this project just starts a sample OAuth 2 Server (not ready for production) on a jetty instance.

To run the complete flow shown in br.com.caelum.oauth.clients package, you will need a resource server configured to use Oltu and the Oauth2SampleFilter.

**However**, with minor fixes it's possible to run the partial flow and obtain the tokens. Of course we'll get a 404 while trying to access the resource server. 

I did those fixes and already push it. Please, if you wish to try it again, you are my guest.

Best
